# Generated by Django 3.1 on 2020-08-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('service_provider_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
